---

- name: Fail on missing aci_vlan_name
  fail: msg="aci_vlan_name not defined"
  when: (aci_vlan_name == "") or (aci_vlan_name is not defined)

- name: Fail on bad aci_vlan_name name format
  fail: msg="Bad format for aci_vlan_name - should be TN|AP|VRF_WORKLOAD -- name provided was {{ aci_vlan_name }}"
  when: aci_vlan_name is not match "(T5)?(CL|DV|Test|Prod)\|[A-Z]+\|([CDTU][FB]|CL)_[A-Z0-9\-]+"

- name: Set TN, AP, EPG vars
  set_fact:
    aci_tn_name: "{{ aci_vlan_name.split('|')[0] | trim }}"
    aci_ap_name: "{{ aci_vlan_name.split('|')[1] | trim }}"
    aci_epg_name: "{{ aci_vlan_name.split('|')[2] | trim }}"

- name: Update tenant for T5
  set_fact: 
    aci_tn_name: "{{ aci_tn_name[2:] }}"
  when: aci_tn_name is match "^T5"  

- name: Set Complex, Work vars
  set_fact:
    aci_complex_name: "{{ aci_epg_name.split('_')[0] | trim }}"
    aci_work_name: "{{ aci_epg_name.split('_')[1] | trim }}"

- name: Set APIC Controller
  set_fact:
    aci_hostname: "{% if aci_tn_name is match '^T5' %}TP-APIC-AP1-1{% elif aci_tn_name is match '(Prod|Test|DV)' %}TP-APIC-HD3-1{% else %}CL-APIC-HD1-1{% endif %}.tvlport.net"

#-name: Check for existing EPG
  #include_tasks:
  #check_epg.yml

- name: Create EPG if it doesn't already exist
  include_tasks:
    create_epg.yml
  #when: "{{ createEPG | default('False') }}"

- name: Add vmm domain to EPG if needed
  include_tasks:
    modify_epg-vmmdomain.yml
  when: "{{ addVMM | default('False') }}"


