---

- name: Fail on bad aci_vlan_name name format
  fail: msg="Bad format for aci_vlan_name - should be <tn>|<ap>|<vrf>_<workload> -- name provided was {{ aci_vlan_name }}"
  when: aci_vlan_name is not match "\w+\|\w+\|\w{2}_\w+"

- name: Set TN, AP, EPG Vars
  set_fact:
    aci_tn_name: "{{ aci_vlan_name.split('|')[0] | trim }}"
    aci_ap_name: "{{ aci_vlan_name.split('|')[1] | trim }}"
    aci_epg_name: "{{ aci_vlan_name.split('|')[2] | trim }}"

- name: Fail on missing TN
  fail: msg="Tenant name was blank in aci_vlan_name -- {{ aci_vlan_name }}"
  when: (aci_tn_name[0] == "") or (aci_tn_name[0] is not defined)

- name: Fail on missing AP
  fail: msg="Application Profile name was blank in aci_vlan_name -- {{ aci_vlan_name }}"
  when: (aci_ap_name[1] == "") or (aci_ap_name[1] is not defined)

- name: Fail on missing EPG
  fail: msg="EPG name was blank in aci_vlan_name -- {{ aci_vlan_name }}"
  when: (aci_epg_name[2] == "") or (aci_epg_name[2] is not defined)

- name: Set APIC Controller default to CertLab
  set_fact: aci_hostname="CL-APIC-HD1-1.tvlport.net"

- name: Update APIC Controller if not CertLab
  set_fact: aci_hostname="TP-APIC-HD3-1.tvlport.net"
  when: (aci_tn_name == "Prod") or (aci_tn_name == "Test") or (aci_tn_name == "DV")

- name: Set Default BD domain if not provided
  set_fact: aci_bd_name="{{ aci_epg_name.split('_')[0] }}-{{ aci_ap_name }}"
  when: (aci_bd_name == "") or (aci_bd_name is not defined)

- name: Fail on bad BD name
  fail: msg="Bad format for aci_bd_name - should be <vrf>-<ap> -- name provided was {{ aci_bd_name }}"
  when: aci_bd_name is not match "\w{2}-\w+"
  
- name: Set VRF Var
  set_fact: aci_vrf_name="{{ aci_bd_name.split('-')[0] | trim }}"

- name: Adjust VRF name if DevLab
  set_fact: aci_vrf_name="DV"
  when: (aci_vrf_name == "DF") or (aci_vrf_name == "DB")
- name: Adjust VRF name if UF
  set_fact: aci_vrf_name="CF"
  when: aci_vrf_name == "UF"
- name: Adjust VRF name if UB
  set_fact: aci_vrf_name="CB"
  when: aci_vrf_name == "UB"

- name: Set Default VM Datacenter to Certlab
  set_fact: vcenter_datacenter="VCSELABATL-NetEng"
- name: Adjust VM Datacenter if Prod
  set_fact: vcenter_datacenter="ADC-UCS"
  when: (aci_bd_name[0:2] == "TF") or (aci_bd_name[0:2] == "TB")
- name: Adjust VM Datacenter if UAT
  set_fact: vcenter_datacenter="ADC_DVPP02"
  when: (aci_bd_name[0:2] == "UF") or (aci_bd_name[0:2] == "UB")
- name: Adjust VM Datacenter if DV or PP
  set_fact: vcenter_datacenter="DAT02-PPUCS-005"
  when: (aci_bd_name[0:2] == "DF") or (aci_bd_name[0:2] == "DB") or (aci_bd_name[0:2] == "CF") or (aci_bd_name[0:2] == "CB")

# Execute the specific OS action playbook
- name: "Execute Configure ACI"
  include_tasks: configure_aci_onprem.yml
#
